"""Event definitions for event-driven engine"""
from enum import Enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional, Dict
import json


class EventType(Enum):
    """Event types in the trading system"""
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"
    RISK_BLOCK = "RISK_BLOCK"
    KILL_SWITCH = "KILL_SWITCH"


@dataclass
class Event:
    """Base event class - all events inherit from this"""
    event_type: EventType
    timestamp: datetime = field(default_factory=datetime.utcnow)
    user_id: int = 0
    strategy_id: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert event to dict"""
        return {
            "event_type": self.event_type.value,
            "timestamp": self.timestamp.isoformat(),
            "user_id": self.user_id,
            "strategy_id": self.strategy_id,
        }


@dataclass
class MarketEvent(Event):
    """Market data event (price, volume, etc)"""
    symbol: str = ""
    price: float = 0.0
    volume: int = 0
    bid: float = 0.0
    ask: float = 0.0
    event_type: EventType = field(default=EventType.MARKET, init=False)


@dataclass
class SignalEvent(Event):
    """Signal generated by strategy (BUY/SELL/NONE)"""
    symbol: str = ""
    signal: str = "NONE"  # BUY, SELL, NONE
    strength: float = 0.0  # 0-1 confidence
    metadata: Dict[str, Any] = field(default_factory=dict)
    event_type: EventType = field(default=EventType.SIGNAL, init=False)


@dataclass
class OrderEvent(Event):
    """Order placement event"""
    symbol: str = ""
    order_type: str = "MARKET"  # MARKET, LIMIT
    side: str = "BUY"  # BUY, SELL
    quantity: float = 0.0
    price: float = 0.0
    status: str = "CREATED"  # CREATED, VALIDATED, SENT, REJECTED, FILLED, PARTIAL, CANCELED
    client_order_id: str = ""
    broker_order_id: str = ""
    event_type: EventType = field(default=EventType.ORDER, init=False)


@dataclass
class FillEvent(Event):
    """Order fill event"""
    symbol: str = ""
    order_id: str = ""
    quantity: float = 0.0
    price: float = 0.0
    commission: float = 0.0
    is_partial: bool = False
    event_type: EventType = field(default=EventType.FILL, init=False)


@dataclass
class RiskBlockEvent(Event):
    """Risk engine blocked a signal"""
    reason: str = ""
    signal: Optional[SignalEvent] = None
    event_type: EventType = field(default=EventType.RISK_BLOCK, init=False)


@dataclass
class KillSwitchEvent(Event):
    """Kill switch activated"""
    reason: str = ""
    event_type: EventType = field(default=EventType.KILL_SWITCH, init=False)
